apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::047365310335:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::047365310335:role/eksctl-eksctl-demo-nodegroup-ng-cb-NodeInstanceRole-Xty42ZRuub5f
      username: system:node:{{EC2PrivateDNSName}}
    
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-23T16:31:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1288"
  uid: 6699c52d-7d8b-410b-b9e5-8f7026fe6adc
