apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::047365310335:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::047365310335:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-q9dJaKnp4g8j
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-29T11:19:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1936"
  uid: 92f247a9-40f4-4f62-9deb-2739c31c9888
