apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::047365310335:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::047365310335:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-oayt2GzMUXtO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-24T10:52:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1298"
  uid: ff617f90-78bd-42cd-9c53-88959da2da58
